import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

describe("completion ledger", () => {
  it("keeps the documented test-count evidence current", () => {
    const ledger = readFileSync(
      join(process.cwd(), "docs", "COMPLETION.md"),
      "utf8",
    );

    expect(ledger).toContain("**329 tests, 35 files passed**");
    expect(ledger).toContain("completion ledger evidence contract");
    expect(ledger).toContain("dark browser chrome metadata");
    expect(ledger).toContain("honest update-promise copy");
    expect(ledger).toContain("icon consistency contract");
    expect(ledger).toContain("desktop app-menu removal policy");
    expect(ledger).toContain("desktop DevTools-disabled policy");
    expect(ledger).toContain("desktop locked-window policy");
    expect(ledger).toContain("desktop window-ownership policy");
    expect(ledger).toContain("desktop permission-denial policy");
    expect(ledger).toContain("desktop certificate-error rejection policy");
    expect(ledger).toContain("desktop redirect guard policy");
    expect(ledger).toContain("desktop frame-navigation guard policy");
    expect(ledger).toContain("desktop drag/drop navigation guard policy");
    expect(ledger).toContain("desktop download prevention policy");
    expect(ledger).toContain("desktop content-protection policy");
    expect(ledger).toContain("desktop power-save blocker policy");
    expect(ledger).toContain("desktop background-throttling policy");
    expect(ledger).toContain("desktop single-instance policy");
    expect(ledger).toContain("desktop shortcut-lock policy");
    expect(ledger).toContain("desktop system-shortcut policy");
    expect(ledger).toContain("desktop storage-partition policy");
    expect(ledger).toContain("desktop launch-argument policy");
    expect(ledger).toContain("desktop IPC sender-origin policy");
    expect(ledger).toContain("desktop web-preferences policy");
    expect(ledger).toContain("explicit frame blocking");
    expect(ledger).toContain("legal effective-date export");
    expect(ledger).toContain("legal sale-state terms copy");
    expect(ledger).toContain("local data deletion guide");
    expect(ledger).toContain("live clean-surface verification");
    expect(ledger).toContain("live homepage identity verification");
    expect(ledger).toContain("live legal effective-date verification");
    expect(ledger).toContain("live public-copy verification");
    expect(ledger).toContain("readiness domain public-page policy");
    expect(ledger).toContain("proof artifact operator guide");
    expect(ledger).toContain("packaged smoke retry");
    expect(ledger).toContain("packaged close-prevention smoke proof");
    expect(ledger).toContain("release publish policy");
    expect(ledger).toContain("packaged manifest metadata contract");
    expect(ledger).toContain("Proof artifact instructions are minimal and redacted");
    expect(ledger).toContain("Windows shell metadata preflight");
    expect(ledger).not.toContain("**328 tests, 35 files passed**");
    expect(ledger).not.toContain("**318 tests, 35 files passed**");
    expect(ledger).not.toContain("**317 tests, 35 files passed**");
    expect(ledger).not.toContain("**316 tests, 35 files passed**");
    expect(ledger).not.toContain("**315 tests, 35 files passed**");
    expect(ledger).not.toContain("**314 tests, 35 files passed**");
    expect(ledger).not.toContain("**313 tests, 35 files passed**");
    expect(ledger).not.toContain("**312 tests, 35 files passed**");
    expect(ledger).not.toContain("**311 tests, 35 files passed**");
    expect(ledger).not.toContain("**310 tests, 35 files passed**");
    expect(ledger).not.toContain("**309 tests, 35 files passed**");
    expect(ledger).not.toContain("**308 tests, 35 files passed**");
    expect(ledger).not.toContain("**305 tests, 34 files passed**");
    expect(ledger).not.toContain("**304 tests, 34 files passed**");
    expect(ledger).not.toContain("**303 tests, 34 files passed**");
    expect(ledger).not.toContain("**302 tests, 34 files passed**");
    expect(ledger).not.toContain("**301 tests, 34 files passed**");
    expect(ledger).not.toContain("**300 tests, 34 files passed**");
    expect(ledger).not.toContain("**299 tests, 34 files passed**");
    expect(ledger).not.toContain("**296 tests, 33 files passed**");
    expect(ledger).toContain("Pages workflow proof/dependency/live-gate coverage");
    expect(ledger).toContain("CI runs repo and launch-drift gates");
    expect(ledger).not.toContain("**295 tests, 33 files passed**");
    expect(ledger).not.toContain("**293 tests, 32 files passed**");
    expect(ledger).not.toContain("**292 tests, 32 files passed**");
    expect(ledger).not.toContain("**291 tests, 32 files passed**");
    expect(ledger).not.toContain("**288 tests, 32 files passed**");
    expect(ledger).not.toContain("**287 tests, 32 files passed**");
    expect(ledger).not.toContain("**285 tests, 32 files passed**");
    expect(ledger).not.toContain("**284 tests, 32 files passed**");
    expect(ledger).not.toContain("**282 tests, 32 files passed**");
    expect(ledger).not.toContain("**281 tests, 32 files passed**");
    expect(ledger).not.toContain("**279 tests, 32 files passed**");
    expect(ledger).not.toContain("**278 tests, 32 files passed**");
    expect(ledger).not.toContain("**277 tests, 32 files passed**");
    expect(ledger).not.toContain("**276 tests, 32 files passed**");
    expect(ledger).not.toContain("**274 tests, 32 files passed**");
    expect(ledger).not.toContain("**269 tests, 30 files passed**");
  });
});
